# Generated by Django 5.0.1 on 2024-04-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='test',
            field=models.CharField(default=0, max_length=11),
        ),
    ]
