# Generated by Django 5.0.1 on 2024-04-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='employees_associated', to='athletics.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='teams_associated', to='athletics.employee'),
        ),
    ]
