# Generated by Django 5.0.1 on 2024-04-09 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0002_event_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='test',
        ),
    ]
