# Generated by Django 5.0.1 on 2024-04-09 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0002_employee_teams_alter_team_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='team_id',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='athlete',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='athletics.athlete'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='scholarship_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
