# Generated by Django 5.0.1 on 2024-03-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0004_remove_team_description_team_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
