# Generated by Django 5.0.1 on 2024-04-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0004_alter_scholarship_athlete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='date',
            new_name='date_awarded',
        ),
    ]
