# Generated by Django 5.0.1 on 2024-04-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0005_remove_event_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='year',
            new_name='date_purchased',
        ),
    ]
