# Generated by Django 5.0.1 on 2024-04-09 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0006_alter_scholarship_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='id',
        ),
        migrations.RemoveField(
            model_name='income',
            name='team_id',
        ),
        migrations.AddField(
            model_name='income',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='athletics.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='income',
            name='income_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(choices=[('DN', 'Donation'), ('GR', 'Grant'), ('FN', 'Fundraiser')], max_length=15),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='type',
            field=models.CharField(choices=[('AC', 'Academic'), ('GR', 'Grant'), ('ATH', 'Athletic'), ('ME', 'Merit'), ('FI', 'Financial Need'), ('OT', 'Other')], max_length=15),
        ),
    ]
