# Generated by Django 5.0.1 on 2024-04-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rank',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='athlete_id',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='team_id',
        ),
        migrations.AddField(
            model_name='athlete',
            name='teams',
            field=models.ManyToManyField(related_name='athletes', to='athletics.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='employees',
            field=models.ManyToManyField(related_name='teams', to='athletics.employee'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='academic_level',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('OT', 'Other')], max_length=2),
        ),
    ]
