# Generated by Django 5.0.1 on 2024-04-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0008_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='date_recorded',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
