# Generated by Django 5.0.1 on 2024-04-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0010_equipment_upfront_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='annual_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
