# Generated by Django 5.0.1 on 2024-04-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0011_alter_equipment_annual_cost_alter_equipment_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='annual_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
