# Generated by Django 5.0.1 on 2024-04-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0012_alter_equipment_annual_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='annual_cost',
            field=models.IntegerField(default=0),
        ),
    ]
