# Generated by Django 5.0.2 on 2024-04-12 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletics', '0013_alter_equipment_annual_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('rank_id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('date_recorded', models.DateField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletics.team')),
            ],
        ),
    ]
